# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-30 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=14)),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
    ]
