# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-30 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='User',
        ),
    ]
